//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.34209
//
//     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <observações/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Transform {
    
    private TransformGroup[] groupField;
    
    private Transform[] transform1Field;
    
    private string dEFField;
    
    private string translationField;
    
    private string scaleField;
    
    private string rotationField;
    
    /// <observações/>
    [System.Xml.Serialization.XmlElementAttribute("Group", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TransformGroup[] Group {
        get {
            return this.groupField;
        }
        set {
            this.groupField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlElementAttribute("Transform")]
    public Transform[] Transform1 {
        get {
            return this.transform1Field;
        }
        set {
            this.transform1Field = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DEF {
        get {
            return this.dEFField;
        }
        set {
            this.dEFField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string translation {
        get {
            return this.translationField;
        }
        set {
            this.translationField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string scale {
        get {
            return this.scaleField;
        }
        set {
            this.scaleField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rotation {
        get {
            return this.rotationField;
        }
        set {
            this.rotationField = value;
        }
    }
}

/// <observações/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class TransformGroup {
    
    private TransformGroupShape[] shapeField;
    
    private string dEFField;
    
    /// <observações/>
    [System.Xml.Serialization.XmlElementAttribute("Shape", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TransformGroupShape[] Shape {
        get {
            return this.shapeField;
        }
        set {
            this.shapeField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DEF {
        get {
            return this.dEFField;
        }
        set {
            this.dEFField = value;
        }
    }
}

/// <observações/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class TransformGroupShape {
    
    private TransformGroupShapeAppearanceImageTexture[] appearanceField;
    
    private TransformGroupShapeIndexedFaceSet[] indexedFaceSetField;
    
    /// <observações/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ImageTexture", typeof(TransformGroupShapeAppearanceImageTexture), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public TransformGroupShapeAppearanceImageTexture[] Appearance {
        get {
            return this.appearanceField;
        }
        set {
            this.appearanceField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlElementAttribute("IndexedFaceSet", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TransformGroupShapeIndexedFaceSet[] IndexedFaceSet {
        get {
            return this.indexedFaceSetField;
        }
        set {
            this.indexedFaceSetField = value;
        }
    }
}

/// <observações/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class TransformGroupShapeAppearanceImageTexture {
    
    private string dEFField;
    
    private string urlField;
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DEF {
        get {
            return this.dEFField;
        }
        set {
            this.dEFField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
}

/// <observações/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class TransformGroupShapeIndexedFaceSet {
    
    private TransformGroupShapeIndexedFaceSetCoordinate[] coordinateField;
    
    private TransformGroupShapeIndexedFaceSetTextureCoordinate[] textureCoordinateField;
    
    private string solidField;
    
    private string texCoordIndexField;
    
    private string coordIndexField;
    
    /// <observações/>
    [System.Xml.Serialization.XmlElementAttribute("Coordinate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TransformGroupShapeIndexedFaceSetCoordinate[] Coordinate {
        get {
            return this.coordinateField;
        }
        set {
            this.coordinateField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlElementAttribute("TextureCoordinate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TransformGroupShapeIndexedFaceSetTextureCoordinate[] TextureCoordinate {
        get {
            return this.textureCoordinateField;
        }
        set {
            this.textureCoordinateField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string solid {
        get {
            return this.solidField;
        }
        set {
            this.solidField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string texCoordIndex {
        get {
            return this.texCoordIndexField;
        }
        set {
            this.texCoordIndexField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string coordIndex {
        get {
            return this.coordIndexField;
        }
        set {
            this.coordIndexField = value;
        }
    }
}

/// <observações/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class TransformGroupShapeIndexedFaceSetCoordinate {
    
    private string dEFField;
    
    private string pointField;
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DEF {
        get {
            return this.dEFField;
        }
        set {
            this.dEFField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string point {
        get {
            return this.pointField;
        }
        set {
            this.pointField = value;
        }
    }
}

/// <observações/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class TransformGroupShapeIndexedFaceSetTextureCoordinate {
    
    private string pointField;
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string point {
        get {
            return this.pointField;
        }
        set {
            this.pointField = value;
        }
    }
}

/// <observações/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class X3D {
    
    private X3DHeadMeta[] headField;
    
    private X3DScene[] sceneField;
    
    private string versionField;
    
    private string profileField;
    
    /// <observações/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("meta", typeof(X3DHeadMeta), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public X3DHeadMeta[] head {
        get {
            return this.headField;
        }
        set {
            this.headField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlElementAttribute("Scene", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public X3DScene[] Scene {
        get {
            return this.sceneField;
        }
        set {
            this.sceneField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string profile {
        get {
            return this.profileField;
        }
        set {
            this.profileField = value;
        }
    }
}

/// <observações/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class X3DHeadMeta {
    
    private string nameField;
    
    private string contentField;
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string content {
        get {
            return this.contentField;
        }
        set {
            this.contentField = value;
        }
    }
}

/// <observações/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class X3DScene {
    
    private X3DSceneNavigationInfo[] navigationInfoField;
    
    private X3DSceneBackground[] backgroundField;
    
    private Transform[] transformField;
    
    /// <observações/>
    [System.Xml.Serialization.XmlElementAttribute("NavigationInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public X3DSceneNavigationInfo[] NavigationInfo {
        get {
            return this.navigationInfoField;
        }
        set {
            this.navigationInfoField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlElementAttribute("Background", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public X3DSceneBackground[] Background {
        get {
            return this.backgroundField;
        }
        set {
            this.backgroundField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlElementAttribute("Transform")]
    public Transform[] Transform {
        get {
            return this.transformField;
        }
        set {
            this.transformField = value;
        }
    }
}

/// <observações/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class X3DSceneNavigationInfo {
    
    private string headlightField;
    
    private string visibilityLimitField;
    
    private string typeField;
    
    private string avatarSizeField;
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string headlight {
        get {
            return this.headlightField;
        }
        set {
            this.headlightField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string visibilityLimit {
        get {
            return this.visibilityLimitField;
        }
        set {
            this.visibilityLimitField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string avatarSize {
        get {
            return this.avatarSizeField;
        }
        set {
            this.avatarSizeField = value;
        }
    }
}

/// <observações/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class X3DSceneBackground {
    
    private string dEFField;
    
    private string groundColorField;
    
    private string skyColorField;
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DEF {
        get {
            return this.dEFField;
        }
        set {
            this.dEFField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string groundColor {
        get {
            return this.groundColorField;
        }
        set {
            this.groundColorField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string skyColor {
        get {
            return this.skyColorField;
        }
        set {
            this.skyColorField = value;
        }
    }
}

/// <observações/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private object[] itemsField;
    
    /// <observações/>
    [System.Xml.Serialization.XmlElementAttribute("Transform", typeof(Transform))]
    [System.Xml.Serialization.XmlElementAttribute("X3D", typeof(X3D))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
